# Generated by Django 5.2.6 on 2025-09-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userauth",
            name="role",
            field=models.CharField(default="developer", max_length=200),
        ),
    ]
