# Generated by Django 5.1.1 on 2025-09-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcategory",
            name="use_cases",
            field=models.JSONField(default=list),
        ),
    ]
