# Generated by Django 5.1.1 on 2025-09-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0003_developerskills"),
        ("projects", "0002_alter_projectcategory_use_cases"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("tech_stack", models.JSONField(default=list)),
                ("project_origin", models.CharField(max_length=200)),
                ("repo_link", models.URLField(blank=True, null=True)),
                ("doc_link", models.URLField(blank=True, null=True)),
                ("presentation_link", models.URLField(blank=True, null=True)),
                ("live_link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="developer_projects",
                        to="developers.developers",
                    ),
                ),
                (
                    "project_categories",
                    models.ManyToManyField(
                        related_name="developer_projects", to="projects.projectcategory"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        related_name="developer_projects", to="developers.skills"
                    ),
                ),
            ],
        ),
    ]
